let if = "(if)"
let else = "(else)"
let while = "(while)"
let digito = "0|1|2|3|4|5|6|7|8|9"
let letra = "a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s"
let identificador = "(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s)((a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s)|(0|1|2|3|4|5|6|7|8|9))*"
let numero = "(0|1|2|3|4|5|6|7|8|9)+"
